value1,value2 = input().split()
value = int(value1) + int(value2)
print(value)
value = int(value1) - int(value2)
print(value)
value = int(value1) * int(value2)
print(value)
value = int(value1) / int(value2)
print(value)
value = int(value1) % int(value2)
print(value)


a, b =  map(int,input().split())
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
